//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA46Team10ASportsFacilityBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingNo { get; set; }
        public int MemberID { get; set; }
        public string FacilityID { get; set; }
        public string TimingID { get; set; }
        public Nullable<System.DateTime> FacilityDate { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string bookstatus { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual Member Member { get; set; }
        public virtual Timing Timing { get; set; }
    }
}
