//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA46Team10ASportsFacilityBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewMemRpt
    {
        public int memberid { get; set; }
        public string membername { get; set; }
        public Nullable<int> total { get; set; }
    }
}
