//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA46Team10ASportsFacilityBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewBookRec
    {
        public int BookingNo { get; set; }
        public string MemberName { get; set; }
        public int memberID { get; set; }
        public string Activity { get; set; }
        public string Venue { get; set; }
        public Nullable<System.DateTime> FacilityDate { get; set; }
        public string TimingID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
    }
}
